version: '3'

services:
  consul_agent:
    image: consul:1.5.2
    environment:
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
    command: agent -bind=${HOST_IP}
                   -client=0.0.0.0 ${JOIN_IP}
                   -ui
    network_mode: 'host'
    ports:
      - '8300:8300'
      - '8301:8301/tcp'
      - '8301:8301/udp'
      - '8302:8302/tcp'
      - '8302:8302/udp'
      - '8400:8400'
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
  proxy_sidecar:
    image: microhq/micro:v1.13.2
    command: --api_handler=proxy
             --api_namespace=go.micro.srv
             --api_address=0.0.0.0:8181
             --registry_address=127.0.0.1:8500
             --register_interval=5
             --register_ttl=10
             --registry=consul
             --enable_stats api
    depends_on:
      - consul_agent
    network_mode: 'host'
    ports:
      - '8181:8181'
